name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Edit package.json 📄
        run: npx json -I -f package.json -e 'this.homepage="${{ secrets.MAINNET_HOMEPAGE_URL }}"'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
        env:
          REACT_APP_ALCHEMY_API_KEY: ${{ secrets.MAINNET_REACT_APP_ALCHEMY_API_KEY }}
          REACT_APP_CHAINID: ${{ secrets.MAINNET_REACT_APP_CHAINID }}
          REACT_APP_ETHERSCAN_API_KEY: ${{ secrets.MAINNET_REACT_APP_ETHERSCAN_API_KEY }}
          REACT_APP_INFURA_API_KEY: ${{ secrets.MAINNET_REACT_APP_INFURA_API_KEY }}
          REACT_APP_SARCO_CONTRACT_ADDRESS: ${{ secrets.MAINNET_REACT_APP_SARCO_CONTRACT_ADDRESS }}

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_PROD }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          REPOSITORY_NAME: ${{ secrets.MAINNET_DEPLOY_REPO_NAME }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
